### ISSUE TITLE
Content is hard to find

### ISSUE THREAD

**Issue by xi** [melmo/melmo.github.io#2]
The content on this page is extremely useful (especially the tipps about leaflet, in my case). Unfortunately, I needed to dig through your code to find the relevant contents, because melmo.github.io only shows "Hello World".

It would be very helpful if you included links to the following pages on the startpage:

- https://melmo.github.io/accessibility/berlin.js/code/dist/
- https://melmo.github.io/accessibility/berlin.js/slides/
- https://melmo.github.io/d3-map-demo/

**Comment by melmo** [comment]
Thanks for the feedback xi, I'm glad you found it useful! I've updated the index page with the links.

**Comment by xi** [comment]
Thanks!
